### ISSUE TITLE
Track 10: Intro to AWS

### ISSUE THREAD

**Issue by subhang-ti** [trilogy-group/tu2k22-vssubhang#13]
- [x] Milestone 1: Add image
- [x] Milestone 2:  Create role and policy
- [x] Milestone 3: SNS
- [x] Milestone 4: VPC and EC2
- [x] Bonus 1
- [x] Bonus 2

**Comment by subhang-ti** [comment]
![Screenshot 2022-08-13 at 6 33 00 PM](https://user-images.githubusercontent.com/110251965/184495398-92979970-43dc-408f-a1cf-dee910a97128.png)
![Screenshot 2022-08-13 at 6 41 10 PM](https://user-images.githubusercontent.com/110251965/184495668-1d83c7b4-c18a-4115-b721-262690462b78.png)
![Screenshot 2022-08-13 at 6 43 06 PM](https://user-images.githubusercontent.com/110251965/184495721-ce3d6d03-7726-45bc-9080-314573019b97.png)
<img width="1091" alt="Screenshot 2022-08-13 at 6 47 15 PM" src="https://user-images.githubusercontent.com/110251965/184495872-6cb3a9a8-1418-480d-8481-3c3a1298fba6.png">
![Screenshot 2022-08-13 at 6 47 59 PM](https://user-images.githubusercontent.com/110251965/184495897-e563ee48-d780-4c51-80b6-6a62cd51d422.png)

**Comment by subhang-ti** [comment]
![Screenshot 2022-08-13 at 8 10 08 PM](https://user-images.githubusercontent.com/110251965/184499076-51e65745-3952-48e4-9408-5ab1f24332ee.png)

**Comment by subhang-ti** [comment]
Bonus 1: If given daily logs I would like to store it in the S3 bucket in the following fashion s3//:<bucket-name>/AppLogs/<Year>/<Month>/<Day>. This would ensure that if we want to search for a log for any particular date, we can input the date in the url and we can get in an O(1) time lookup. Use Athena to query logs and we can remove certain % of normal logs. Use Expiration Lifecycle method to remove old logs.

**Comment by sirjan-cn** [comment]
LGTM, if interested, read up more for bonus 1 here: https://repost.aws/questions/QUjQHGAO_nQd-PsIKsvfH3HA/partitioning-s-3-access-logs-to-optimize-athena-queries
