### ISSUE TITLE
Track 15: Parallel Processing

### ISSUE THREAD

**Issue by subhang-ti** [trilogy-group/tu2k22-vssubhang#23]
- [x] Milestone 1: Codejudge Submission
- [ ] Bonus

**Comment by subhang-ti** [comment]
![Screenshot 2022-08-20 at 2 02 40 AM](https://user-images.githubusercontent.com/110251965/185707282-a85eaa85-0d2d-460c-8e06-dcaacb5ec9dd.png)

**Comment by rakshit-ti** [comment]
can we close this?
